#! perl
# Copyright (C) 2008-2009, Parrot Foundation.
# $Id$

=head1 A harness for Parrot Markdown

=head2 Synopsis

    cd languages && make markdown.test

    cd languages && perl t/harness --languages=markdown

    cd languages && perl -I../lib -Imarkdown/t markdown/t/harness --files

    cd languages && perl -I../lib -Imarkdown/t markdown/t/harness

    cd languages && perl -I../lib -Imarkdown/t markdown/t/harness markdown/t/examples.t

=head2 Description

If I'm called with a single
argument of "--files", I just return a list of files to process.
This list is one per line, and is relative to the languages dir.

If I'm called with no args, I run the complete suite.

Otherwise I run the tests that were passed on the command line.

=cut

use strict;
use warnings;
use 5.008;

use Parrot::Test::Harness language => 'markdown';

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:

